prob1 : prob1.cpp AbstractGraph.hpp AdjacencyList.hpp AdjacencyMatrix.hpp GraphAdjacencyBase.hpp seqLinearList.hpp UndirectedGraph.hpp list.hpp
	g++ -o prob1 prob1.cpp

prob2 : prob2.cpp AbstractGraph.hpp AdjacencyList.hpp AdjacencyMatrix.hpp GraphAdjacencyBase.hpp seqLinearList.hpp UndirectedGraph.hpp list.hpp
	g++ -o prob2 prob2.cpp

prob3 : prob3.cpp AbstractGraph.hpp AdjacencyList.hpp AdjacencyMatrix.hpp GraphAdjacencyBase.hpp seqLinearList.hpp UndirectedGraph.hpp list.hpp
	g++ -o prob3 prob3.cpp

prob4 : prob4.cpp AbstractGraph.hpp AdjacencyList.hpp AdjacencyMatrix.hpp DirectedGraph.hpp GraphAdjacencyBase.hpp seqLinearList.hpp list.hpp
	g++ -o prob4 prob4.cpp

clean :
	rm prob1 prob2 prob3 prob4 
